import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ChakraProviderWrapper from "./chakra_provider";
import { ChakraProvider } from "@chakra-ui/react";
import RouteMiddleware from "./private";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
     <body className={inter.className}>
     <ChakraProvider>
      <RouteMiddleware> 
      {children}
      </RouteMiddleware>
      </ChakraProvider>
     </body>
    </html>
  );
}
